name: Deploy to Azure VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug SSH Key
      run: echo "${{ secrets.AZURE_SSH_KEY }}"

    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_USER }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        script: |
          cd /var/www/infinity_agents
          git pull origin main
          sudo systemctl restart infinity_agents